- hosts: all
  tasks:
    - name: Create new users
      user:
        name: '{{ item.name }}'
        uid:  '{{ item.uid }}'
        comment:  '{{ item.comment }}' 
        state: present

      loop:
        - name: mike
          uid: 1001
          comment: Administrator

        - name: sandra
          uid: 1002
          comment: Techie
